[package]
name = "wk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
imgui = "0.11.0"
imgui-wgpu = "0.24.0"
pollster = "0.3.0"
raw-window-handle = "0.5.2"
wgpu = "0.17.0"
# don't really need these, but just for the imgui-sdl2 original example to get it working
gl = "0.10.0"
imgui-opengl-renderer = "0.12.1"

[dependencies.sdl2]
git = "https://github.com/rust-sdl2/rust-sdl2"
default-features = false
features = ["raw-window-handle"]
