[package]
name = "wk"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.17.0"
env_logger = "0.10.0"
imgui = "0.11.0"
pollster = "0.3.0"
raw-window-handle = "0.5.2"
bytemuck = { version = "1.13", features = ["derive"] }
smallvec = "1"
clap = { version = "4.4.11", features = ["derive"] }

[dependencies.sdl2]
git = "https://github.com/rust-sdl2/rust-sdl2"
default-features = false
features = ["raw-window-handle"]
