[package]
name = "wk"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.17.2"
env_logger = "0.11.6"
imgui = "0.12.0"
pollster = "0.4.0"
raw-window-handle = "0.6.2"
bytemuck = { version = "1.21.0", features = ["derive"] }
smallvec = "1.13.2"
clap = { version = "4.5.28", features = ["derive"] }

[dependencies.sdl2]
git = "https://github.com/rust-sdl2/rust-sdl2"
default-features = false
features = ["raw-window-handle"]
rev = "edc92fe3285d248fd053a62414365ba19faadbd4"
